# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Trausnitz Games
email: info@trausnitz-games.de
description: >- # this means to ignore newlines until "baseurl:"
  "Ein kleines Indie-Spielestudio aus Bayern, das sich auf textbasierte Adventure-Spiele spezialisiert hat."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  herrschwaiger

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "de-DE"

title: "Trausnitz Games"
subtitle: "Intranet"
name: "Trausnitz Games"
description: "Ein kleines Indie-Spielestudio aus Bayern, das sich auf textbasierte Adventure-Spiele spezialisiert hat."
logo: "assets/images/logo.png"

include: ["_pages"]

breadcrumbs: true  # disabled by default
search: true

plugins:
  - jekyll-feed
  - jekyll-include-cache

#collections:
#  databases:
#    output: true # Sorgt dafür, dass die Seiten generiert werden
#    permalink: /databases/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

words_per_minute: 100

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-5DSLWWS1RS"
    anonymize_ip: false # default




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
